using EscolaWebForms.svc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace EscolaWebForms.Web
{
    public partial class ListaAlunos : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                gridAlunos();
            }

        }

        protected void gridAlunos()
        {
            svcAluno insSvcAluno = new svcAluno();

            var listAlunos = insSvcAluno.listaAlunos();

            gvAlunos.DataSource = listAlunos;
            gvAlunos.AllowPaging = true;
            gvAlunos.PageSize = 10;
            gvAlunos.AutoGenerateEditButton = true;
            gvAlunos.AutoGenerateDeleteButton = true;
            gvAlunos.AlternatingRowStyle.BorderWidth = 1;
            
            gvAlunos.DataBind();
        }

        protected void gvAlunos_OnPageIndexChanged(object sender, GridViewPageEventArgs e)
        {
            gvAlunos.PageIndex = e.NewPageIndex;
            gvAlunos.DataBind();
        }

        protected void edit_RowEditing(object sender, GridViewEditEventArgs e)
        {
            var gridEdit = gvAlunos.Rows[e.NewEditIndex].Cells[1];

           
            Context.Items.Add("id", gridEdit.Text);
            Server.Transfer("~/EditarAluno.aspx");
        }

    }
}