//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaWebForms.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RESDisciplina {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESDisciplina() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscolaWebForms.Data.RESDisciplina", typeof(RESDisciplina).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update disciplina
        ///set nome = @nome
        ///where id = @id.
        /// </summary>
        internal static string atualizaDisciplina {
            get {
                return ResourceManager.GetString("atualizaDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from disciplina
        ///where id = @id.
        /// </summary>
        internal static string buscaDisciplina {
            get {
                return ResourceManager.GetString("buscaDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select coalesce(max(id),0)+1 from disciplina.
        /// </summary>
        internal static string buscaNovoId {
            get {
                return ResourceManager.GetString("buscaNovoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from disciplina
        ///where id = @id.
        /// </summary>
        internal static string deleteDisciplina {
            get {
                return ResourceManager.GetString("deleteDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into disciplina (nome) values(@nome).
        /// </summary>
        internal static string inserirDisciplinas {
            get {
                return ResourceManager.GetString("inserirDisciplinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from disciplina.
        /// </summary>
        internal static string listaDisciplinas {
            get {
                return ResourceManager.GetString("listaDisciplinas", resourceCulture);
            }
        }
    }
}
