//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaWebForms.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RESRegistroNotas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESRegistroNotas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscolaWebForms.Data.RESRegistroNotas", typeof(RESRegistroNotas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update registroNotas 
        ///set nota1 = @nota1, nota2 = @nota2, nota3 = @nota3,
        ///nota4 = @nota4, media = @media
        ///where id = @id.
        /// </summary>
        internal static string AtualizaNotas {
            get {
                return ResourceManager.GetString("AtualizaNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from registroNotas where id = @id.
        /// </summary>
        internal static string buscaNotas {
            get {
                return ResourceManager.GetString("buscaNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select n.id, n.aluno, a.nome as nomeAluno, d.nome as nomeDisciplina, coalesce(n.nota1,0) as nota1, 
        ///coalesce(n.nota2,0) as nota2, coalesce(n.nota3,0) as nota3, 
        ///coalesce(n.nota4,0) as nota4, coalesce(n.media,0) as media
        ///from registroNotas n
        ///join aluno a on n.aluno = a.cpf
        ///join disciplina d on n.disciplina = d.id;.
        /// </summary>
        internal static string gvListaNotas {
            get {
                return ResourceManager.GetString("gvListaNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into registroNotas (aluno, disciplina) values (@aluno, @disciplina).
        /// </summary>
        internal static string insereNotasAlunoDisciplina {
            get {
                return ResourceManager.GetString("insereNotasAlunoDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select n.id, n.aluno, n.disciplina,  coalesce(n.nota1,0) as nota1, 
        ///coalesce(n.nota2,0) as nota2, coalesce(n.nota3,0) as nota3, 
        ///coalesce(n.nota4,0) as nota4, coalesce(n.media,0) as media
        ///from registroNotas n.
        /// </summary>
        internal static string listaNotas {
            get {
                return ResourceManager.GetString("listaNotas", resourceCulture);
            }
        }
    }
}
